"""Added comment_content to comment

Revision ID: f5e625fbad5e
Revises: 
Create Date: 2024-05-28 10:39:46.740596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5e625fbad5e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('comment_content', sa.String(), nullable=True))
    op.add_column('post', sa.Column('Post_title', sa.String(), nullable=True))
    op.add_column('post', sa.Column('Post_content', sa.String(), nullable=True))
    op.drop_column('post', 'mobile_no')
    op.drop_column('post', 'investor_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('investor_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('post', sa.Column('mobile_no', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('post', 'Post_content')
    op.drop_column('post', 'Post_title')
    op.drop_column('comment', 'comment_content')
    # ### end Alembic commands ###
